<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { BadgeCheck, Phone, ShieldAlert } from "lucide-vue-next";
import H5Header from "../components/H5Header.vue";
import { activeRegion } from "../region";
import { createServiceOrder, fetchCommercialServices, fetchPaymentCapabilities, type CommercialService } from "../api";
const services=ref<CommercialService[]>([]);const payment=ref<{available:boolean;provider:string;message:string}|null>(null);const loading=ref(true);const error=ref("");const notice=ref("");
async function load(){loading.value=true;error.value="";try{[services.value,payment.value]=await Promise.all([fetchCommercialServices(activeRegion.value.region_code),fetchPaymentCapabilities()]);}catch{error.value="合作服务暂时无法读取。";}finally{loading.value=false;}}
async function reserve(item:CommercialService){if(!localStorage.getItem("jianda_resident_token")){location.assign(`/resident/login?redirect=${encodeURIComponent('/trusted-services')}`);return;}if(!window.confirm(`确认创建“${item.name}”待支付订单吗？`))return;try{const result=await createServiceOrder(item.id);notice.value=`订单 ${result.orderNo} 已创建。${result.payment.message}`;}catch(e:any){error.value=e?.response?.data?.message||"订单创建失败。";}}
onMounted(load);watch(()=>activeRegion.value.region_code,load);
</script>
<template><div class="h5-page"><H5Header/><main class="h5-main trusted-services"><header class="app-section-head"><BadgeCheck/><div><h1>合作服务</h1><p>{{ activeRegion.street_or_town }} · 仅展示已核验服务商，与政府公开信息分开展示。</p></div></header><p class="commercial-disclosure"><ShieldAlert/>以下为合作服务，不是政府办事事项。请先核对服务范围、价格和退款规则。</p><p v-if="payment&&!payment.available" class="payment-unavailable">{{payment.message}}</p><p v-if="notice" class="compact-success">{{notice}} <RouterLink to="/orders">查看我的订单</RouterLink></p><p v-if="error" class="form-error">{{error}}</p><div v-if="loading" class="list-skeleton"><i v-for="n in 3" :key="n"/></div><section v-else class="trusted-service-list"><article v-for="item in services" :key="item.id"><header><span>合作服务</span><b><BadgeCheck/>服务商已核验</b></header><h2>{{item.name}}</h2><p>{{item.description}}</p><dl><div><dt>服务机构</dt><dd>{{item.provider_name}}</dd></div><div><dt>服务范围</dt><dd>{{item.service_area}}</dd></div><div><dt>价格</dt><dd>¥{{(item.price_cents/100).toFixed(2)}}</dd></div><div v-if="item.refund_policy"><dt>退款规则</dt><dd>{{item.refund_policy}}</dd></div></dl><footer><a v-if="item.contact_phone" :href="`tel:${item.contact_phone}`"><Phone/>联系机构</a><button @click="reserve(item)">预约服务</button></footer></article><div v-if="!services.length" class="empty"><BadgeCheck/><b>当前地区暂无已核验合作服务</b><p>平台不会用演示商家补充列表。</p></div></section></main></div></template>
<style scoped>.trusted-services{padding-bottom:40px}.commercial-disclosure,.payment-unavailable,.compact-success{display:flex;gap:10px;align-items:flex-start;padding:14px 16px}.commercial-disclosure{background:#fff8e9;border-left:4px solid #bd741e}.payment-unavailable{background:#f3f5f4;color:#47544f}.trusted-service-list{display:grid;gap:14px}.trusted-service-list article{padding:20px;background:#fff;border:1px solid #d9e1de}.trusted-service-list header,.trusted-service-list footer{display:flex;justify-content:space-between;gap:12px}.trusted-service-list header span{color:#9a5716;font-weight:700}.trusted-service-list header b{display:flex;gap:5px;color:#176b63}.trusted-service-list h2{margin:16px 0 8px}.trusted-service-list dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}.trusted-service-list dt{color:#68746f;font-size:14px}.trusted-service-list dd{margin:3px 0;font-weight:700}.trusted-service-list footer{align-items:center;margin-top:18px}.trusted-service-list footer a{display:flex;gap:5px}.trusted-service-list button{min-height:48px;padding:0 20px;border:0;background:#176b63;color:white;font-weight:700}@media(max-width:480px){.trusted-service-list dl{grid-template-columns:1fr}}</style>
