import { expect, test, type Page, type Route } from "@playwright/test";
const h5Url=process.env.JIANDA_H5_TEST_URL??"http://127.0.0.1:5174";
const institutionUrl=process.env.JIANDA_INSTITUTION_URL??"http://127.0.0.1:5173";
async function json(route:Route,data:unknown){await route.fulfill({status:200,contentType:"application/json; charset=utf-8",body:JSON.stringify({code:0,message:"成功",data})});}
const profile={id:1,username:"demo_chen",nickname:"陈阿姨",district:"宝山区",streetOrTown:"大场镇",regionCode:"310113102",demo:true};
const post={id:9,category:"互助",content:"请问社区智能手机课堂在哪里报名？",region_code:"310113102",district:"宝山区",street_or_town:"大场镇",status:"VISIBLE",is_demo:true,created_at:"2026-08-23T08:00:00+08:00",nickname:"陈阿姨",user_is_demo:true,like_count:2,comment_count:1,media:[{id:7,mimeType:"image/jpeg",width:640,height:480,url:"/api/public/community/media/7",thumbnailUrl:"/api/public/community/media/7/thumbnail"}]};
async function h5Mocks(page:Page,calls:string[]){await page.route("**/*",async route=>{const url=new URL(route.request().url());if(url.pathname.includes("/community/media/7/thumbnail"))return route.fulfill({status:200,contentType:"image/png",body:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64")});if(!url.pathname.startsWith("/api/"))return route.continue();if(url.pathname==="/api/public/resident/login")return json(route,{token:"resident-token",profile});if(url.pathname==="/api/public/resident/register")return json(route,{token:"resident-token",profile:{...profile,demo:false,username:"new_resident",nickname:"新居民"}});if(url.pathname==="/api/public/resident/registration-capabilities")return json(route,{usernamePassword:true,sms:{enabled:false,message:"短信注册尚未启用，请使用用户名和密码注册"}});if(url.pathname==="/api/public/resident/me")return json(route,profile);if(url.pathname==="/api/public/community/media"&&route.request().method()==="POST"){calls.push("media");return json(route,{id:8,mimeType:"image/png",width:1,height:1,url:"/api/public/community/media/8",thumbnailUrl:"/api/public/community/media/8/thumbnail"});}if(url.pathname==="/api/public/community/posts"&&route.request().method()==="GET")return json(route,[post]);if(url.pathname==="/api/public/community/posts"&&route.request().method()==="POST"){calls.push("post");return json(route,{id:10});}if(url.pathname.endsWith("/like")){calls.push("like");return json(route,{liked:true});}if(url.pathname.endsWith("/comments")){calls.push("comment");return json(route,{created:true});}if(url.pathname.endsWith("/report")){calls.push("report");return json(route,null);}return json(route,null);});}

test("居民 DEMO 登录后完成邻里发布、点赞、评论和举报",async({page})=>{const calls:string[]=[];await h5Mocks(page,calls);await page.setViewportSize({width:375,height:812});await page.goto(`${h5Url}/resident/login`);await page.getByLabel("用户名").fill("demo_chen");await page.getByLabel("密码").fill("Resident@123");await page.getByRole("button",{name:"登录",exact:true}).click();await expect(page).toHaveURL(/\/profile$/);await page.goto(`${h5Url}/neighborhood`);await expect(page.getByRole("heading",{name:"大场邻里"})).toBeVisible();await page.getByLabel("分享一件对邻里有用的事").fill("想请教邻里一件社区服务事项");await page.getByRole("button",{name:"发布",exact:true}).click();await expect.poll(()=>calls).toContain("post");await page.getByRole("button",{name:"2"}).click();await expect.poll(()=>calls).toContain("like");page.once("dialog",dialog=>dialog.accept("这是一条友善的测试评论"));await page.getByRole("button",{name:"1"}).click();await expect.poll(()=>calls).toContain("comment");page.once("dialog",dialog=>dialog.accept("这是自动测试举报原因"));await page.getByRole("button",{name:"举报"}).click();await expect.poll(()=>calls).toContain("report");await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();});

test("游客受保护操作带 redirect 登录并可注册",async({page})=>{const calls:string[]=[];await h5Mocks(page,calls);await page.setViewportSize({width:375,height:812});await page.goto(`${h5Url}/neighborhood`);await page.getByRole("button",{name:/登录居民账号/}).click();await expect(page).toHaveURL(/resident\/login\?redirect=\/neighborhood/);await page.getByRole("link",{name:/使用用户名和密码注册/}).click();await expect(page.getByText("短信注册尚未启用，请使用用户名和密码注册")).toBeVisible();await page.getByLabel("用户名").fill("new_resident");await page.getByLabel("昵称").fill("新居民");await page.getByLabel(/^密码/).fill("Secure123");await page.getByLabel("确认密码").fill("Secure123");await page.getByRole("button",{name:"注册并登录"}).click();await expect(page).toHaveURL(/\/neighborhood$/);});

test("居民登录后可选择预览移除和发布图片",async({page})=>{const calls:string[]=[];await h5Mocks(page,calls);await page.addInitScript(()=>localStorage.setItem("jianda_resident_token","resident-token"));await page.setViewportSize({width:375,height:812});await page.goto(`${h5Url}/neighborhood`);const chooser=page.locator('input[type="file"]');await chooser.setInputFiles({name:"neighbor.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64")});await expect(page.getByAltText("待发布图片 1")).toBeVisible();await page.getByRole("button",{name:"移除图片 1"}).click();await expect(page.getByAltText("待发布图片 1")).toHaveCount(0);await chooser.setInputFiles({name:"neighbor.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64")});await page.getByLabel("分享一件对邻里有用的事").fill("带图片的真实邻里消息");await page.getByRole("button",{name:"发布",exact:true}).click();await expect.poll(()=>calls).toEqual(expect.arrayContaining(["media","post"]));await expect(page.getByAltText("陈阿姨发布的图片 1")).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();});

test("平台管理员可以隐藏和恢复被举报帖子",async({page})=>{const statuses:string[]=[];await page.addInitScript(()=>{localStorage.setItem("jianda_token","platform-token");localStorage.setItem("jianda_user_info",JSON.stringify({role:"PLATFORM_ADMIN",displayName:"平台管理员"}));});await page.route("**/*",async route=>{const url=new URL(route.request().url());if(!url.pathname.startsWith("/api/"))return route.continue();if(url.pathname==="/api/community-admin/posts"&&route.request().method()==="GET")return json(route,[{id:9,content:post.content,status:statuses.at(-1)??"REPORTED",created_at:post.created_at,nickname:"陈阿姨",report_count:1}]);if(url.pathname.endsWith("/status")){statuses.push(JSON.parse(route.request().postData()||"{}").status);return json(route,null);}return json(route,null);});await page.goto(`${institutionUrl}/community-moderation`);await expect(page.getByText("已举报，待处理")).toBeVisible();page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:"隐藏"}).click();await expect.poll(()=>statuses).toEqual(["HIDDEN"]);await expect(page.getByRole("cell",{name:"已隐藏"})).toBeVisible();page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:"恢复"}).click();await expect.poll(()=>statuses).toEqual(["HIDDEN","VISIBLE"]);});
