import { createRouter, createWebHistory } from "vue-router";

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: "/", component: () => import("./views/HomeView.vue"), meta: { title: "首页", showBack: false } },
    { path: "/listen", component: () => import("./views/ListenView.vue"), meta: { title: "听一听", showBack: false } },
    { path: "/neighborhood", component: () => import("./views/NeighborhoodView.vue"), meta: { title: "邻里", showBack: false } },
    { path: "/resident/login", component: () => import("./views/ResidentLoginView.vue"), meta: { title: "居民登录", showBack: true, backTo: "/profile" } },
    { path: "/resident/register", component: () => import("./views/ResidentRegisterView.vue"), meta: { title: "居民注册", showBack: true, backTo: "/resident/login" } },
    { path: "/news", component: () => import("./views/NewsFeedView.vue"), meta: { title: "权威资讯", showBack: true, backTo: "/" } },
    { path: "/assistant", component: () => import("./views/AssistantView.vue"), meta: { title: "简达助手", showBack: false } },
    { path: "/services", component: () => import("./views/ServicesView.vue"), meta: { title: "服务", showBack: false } },
    { path: "/services/health", component: () => import("./views/ServiceChannelView.vue"), meta: { title: "社区卫生", serviceKind: "health", showBack: true, backTo: "/services" } },
    { path: "/services/meals", component: () => import("./views/ServiceChannelView.vue"), meta: { title: "长者食堂", serviceKind: "meals", showBack: true, backTo: "/services" } },
    { path: "/services/contacts", component: () => import("./views/ServiceChannelView.vue"), meta: { title: "便民电话", serviceKind: "contacts", showBack: true, backTo: "/services" } },
    { path: "/services/guides", component: () => import("./views/ServiceChannelView.vue"), meta: { title: "办事指南", serviceKind: "guides", showBack: true, backTo: "/services" } },
    { path: "/activities", component: () => import("./views/ServiceChannelView.vue"), meta: { title: "活动报名", serviceKind: "activities", showBack: true, backTo: "/services" } },
    { path: "/trusted-services", component: () => import("./views/TrustedServicesView.vue"), meta: { title: "合作服务", showBack: true, backTo: "/services" } },
    { path: "/orders", component: () => import("./views/ServiceOrdersView.vue"), meta: { title: "我的订单", showBack: true, backTo: "/profile" } },
    { path: "/membership", component: () => import("./views/MembershipView.vue"), meta: { title: "简达会员", showBack: true, backTo: "/profile" } },
    { path: "/profile", component: () => import("./views/ProfileView.vue"), meta: { title: "我的", showBack: false } },
    { path: "/category/:name", component: () => import("./views/ListView.vue"), meta: { title: "内容分类", showBack: true, backTo: "/news" } },
    { path: "/search", component: () => import("./views/ListView.vue"), meta: { title: "搜索", showBack: true, backTo: "/" } },
    { path: "/guide/:slug", component: () => import("./views/DetailView.vue"), meta: { title: "办事指南", showBack: true, backTo: "/services" } },
    { path: "/news/:slug", component: () => import("./views/DetailView.vue"), meta: { title: "权威资讯", showBack: true, backTo: "/news" } },
    { path: "/steps/:slug", component: () => import("./views/DetailView.vue"), meta: { title: "办理步骤", showBack: true, backTo: "/services" } },
    { path: "/favorites", component: () => import("./views/FavoritesView.vue"), meta: { title: "我的收藏", showBack: true, backTo: "/profile" } },
    { path: "/history", component: () => import("./views/HistoryView.vue"), meta: { title: "历史浏览", showBack: true, backTo: "/profile" } },
    { path: "/reminders", component: () => import("./views/RemindersView.vue"), meta: { title: "我的提醒", showBack: true, backTo: "/profile" } },
    { path: "/assistant/history", component: () => import("./views/AssistantHistoryView.vue"), meta: { title: "历史会话", showBack: true, backTo: "/assistant" } },
    { path: "/settings", component: () => import("./views/SettingsView.vue"), meta: { title: "阅读设置", showBack: true, backTo: "/profile" } },
    { path: "/original/:slug", component: () => import("./views/OriginalView.vue"), meta: { title: "查看原文", showBack: true }, beforeEnter: (to) => { const slug = String(to.params.slug); const kind = to.query.from === "news" ? "news" : "guide"; to.meta.backTo = `/${kind}/${slug}`; } },
    { path: "/original-file/:slug", component: () => import("./views/OriginalFileView.vue"), meta: { title: "查看原文件", showBack: true }, beforeEnter: (to) => { const slug = String(to.params.slug); const kind = to.query.from === "news" ? "news" : "guide"; to.meta.backTo = `/${kind}/${slug}`; } },
  ],
});
export default router;
